### ISSUE TITLE
Keep sync when using multipliers 

### ISSUE THREAD

**Issue by modalexii** [d00mfish/BPMtoOSC#2]
Feature suggestion: Personally I would prefer if the /2 and x2 functions did not break sync. Keep determining BPM real time but send the value /2 or x2. Using BPMtoOSC with deep bass music which often has a slow feel but fast high-end percussion (hats, etc) results in BPM reading double the nominal speed of the song - knowing that we're playing deep bass all night, i'd like to just click /2 and let the auto-magic keep happening.

This project is excellent, btw. Elegant, functional.

**Comment by d00mfish** [comment]
Hey, great to hear that my program is helping you!
I like the Idea. It would be difficult adding a function to send more beats than aubio detects as this would need an extra thread to run, therefore adds complexity and also latency.
But fortunately you are more interested in reducing the BPM, so I added a new "halftime" button below the SYNC button. I think the usage is self-explanatory.
Check out this new release: [v1.2.0](https://github.com/d00mfish/BPMtoOSC/tree/v1.2.0)
Also I could reduce the filesize to half of the old release.

Hope this helps you,

Cheers!

**Comment by modalexii** [comment]
Fantastic, thank you!
